// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt3APJ9D2bsrb1yqinIfHinNWMYMvLLPA',
    appId: '1:81329552815:web:3c3752f1f2109075bbc35a',
    messagingSenderId: '81329552815',
    projectId: 'fir-backend-8121c',
    authDomain: 'fir-backend-8121c.firebaseapp.com',
    storageBucket: 'fir-backend-8121c.firebasestorage.app',
    measurementId: 'G-W94S43NF62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9OSUQeP-DwlIM1gcneSMbgqCiiy-I9Hc',
    appId: '1:81329552815:android:b630b660b2893129bbc35a',
    messagingSenderId: '81329552815',
    projectId: 'fir-backend-8121c',
    storageBucket: 'fir-backend-8121c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUAFd42A-bYEWpA0Q-ioPRBd30p6j4m1Y',
    appId: '1:81329552815:ios:833bfdd64a5785b2bbc35a',
    messagingSenderId: '81329552815',
    projectId: 'fir-backend-8121c',
    storageBucket: 'fir-backend-8121c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt3APJ9D2bsrb1yqinIfHinNWMYMvLLPA',
    appId: '1:81329552815:web:11d3868bd2ab90b6bbc35a',
    messagingSenderId: '81329552815',
    projectId: 'fir-backend-8121c',
    authDomain: 'fir-backend-8121c.firebaseapp.com',
    storageBucket: 'fir-backend-8121c.firebasestorage.app',
    measurementId: 'G-55DBVQFFC5',
  );
}
